# Generated by Django 5.2 on 2025-04-12 18:32

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(default='dis', max_length=3, verbose_name='status do item')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='objects', variations={'medium': (600, 400), 'thumb': (300, 300, True)})),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objeto_categoria', to='objetos.categoria')),
            ],
        ),
    ]
