# Generated by Django 5.2 on 2025-04-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
